version: '3.9'

services:

  ep-backup-be-prod:
    container_name: ep-backup-be-prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABSE=postgres
      - PGPASSWORD=postgres
    ports:
      - '1400:1400'
    networks:
      - ep-backup-tool-be

  postgres:
    image: 'postgres:13'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ep-backup-tool-be

networks:
  ep-backup-tool-be:
    driver: bridge
