version: '3.9'

services:

  ep-backup-be-prod:
    container_name: ep-backup-be-prod
    build:
      context: .
      dockerfile: Dockerfile prod
    restart: unless-stopped
    ports:
      - '1400:1400'
