version: '3.9'

services:

  vanlang-be-prod:
    container_name: vanlang-be-prod
    build:
      context: .
      dockerfile: Dockerfile prod
    restart: unless-stopped
    ports:
      - '1400:1400'
